version: "3.8"

services:
  database:
    container_name: db
    image: postgres:13.4-alpine
    restart: always
    user: postgres  # importante definir o usuário
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres  # senha padrão
      - POSTGRES_USER=postgres  # usuário padrão
      - POSTGRES_DB=db  # necessário porque foi configurado assim no settings
    ports:
      - 5433:5432  # repare na porta externa 5433
    networks:
      - postgres

steps:
 uses: actions/checkout@v1
      - run: npm ci
        working-directory: ./postgres
      - run: node client.js
        working-directory: ./postgres
- name: Install dependencies
  run: 
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest-django
    pip install npm
-name: Run migrations
 run: python manage.py migrate
-name: Run tests
 run: py.test 